//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace BAGA
{
    	[Serializable()]
        [DataContractAttribute(IsReference=true)]
    public partial class CustomersinPastYear : POCO.State.StateObject
    {
        #region Primitive Properties
        [DataMember]
         public int COntactID
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public Nullable<int> PrimaryDesintation
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public int CustomerTypeID
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public Nullable<System.DateTime> InitialDate
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public Nullable<int> SecondaryDestination
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public Nullable<int> PrimaryActivity
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public Nullable<int> SecondaryActivity
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public string Notes
        {
    		   get{return _notes;} 
    			set
     				{
      				{ _notes = value;}
    				}
    
    	
        }
        private string _notes;
        [DataMember]
         public string FirstName
        {
    		   get{return _firstName;} 
    			set
     				{
    					if (value != null && value.Length > 50) 
    					 {throw new ArgumentException("FirstName must be less than 50 characters");}
    			    else
      				{ _firstName = value;}
    				}
    
    	
        }
        private string _firstName;
        [DataMember]
         public string LastName
        {
    		   get{return _lastName;} 
    			set
     				{
    					if (value != null && value.Length > 50) 
    					 {throw new ArgumentException("LastName must be less than 50 characters");}
    			    else
      				{ _lastName = value;}
    				}
    
    	
        }
        private string _lastName;
        [DataMember]
         public string Title
        {
    		   get{return _title;} 
    			set
     				{
    					if (value != null && value.Length > 50) 
    					 {throw new ArgumentException("Title must be less than 50 characters");}
    			    else
      				{ _title = value;}
    				}
    
    	
        }
        private string _title;
        [DataMember]
         public System.DateTime AddDate
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public System.DateTime ModifiedDate
        {
    	        get;
    		set;
    	
        }

        #endregion
    }
}
