//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace BAGA
{
    	[Serializable()]
        [DataContractAttribute(IsReference=true)]
    public partial class Destination : POCO.State.StateObject
    {
        #region Primitive Properties
        [DataMember]
         public int DestinationID
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public string Name
        {
    		   get{return _name;} 
    			set
     				{
    					if (value != null && value.Length > 50) 
    					 {throw new ArgumentException("Name must be less than 50 characters");}
    			    else
      				{ _name = value;}
    				}
    
    	
        }
        private string _name;

        #endregion
        #region Navigation Properties
    
        [DataMember]
    	public FixupCollection<Customer> PrimaryPrefCustomers
        {
            get
            {
                if (_primaryPrefCustomers == null)
                {
                    var newCollection = new FixupCollection<Customer>();
                    newCollection.CollectionChanged += FixupPrimaryPrefCustomers;
                    _primaryPrefCustomers = newCollection;
                }
                return _primaryPrefCustomers;
            }
            set
            {
                if (!ReferenceEquals(_primaryPrefCustomers, value))
                {
                    var previousValue = _primaryPrefCustomers as FixupCollection<Customer>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPrimaryPrefCustomers;
                    }
                    _primaryPrefCustomers = value;
                    var newValue = value as FixupCollection<Customer>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPrimaryPrefCustomers;
                    }
                }
            }
        }
        private FixupCollection<Customer> _primaryPrefCustomers;
    
        [DataMember]
    	public FixupCollection<Customer> SecondaryPrefCustomers
        {
            get
            {
                if (_secondaryPrefCustomers == null)
                {
                    var newCollection = new FixupCollection<Customer>();
                    newCollection.CollectionChanged += FixupSecondaryPrefCustomers;
                    _secondaryPrefCustomers = newCollection;
                }
                return _secondaryPrefCustomers;
            }
            set
            {
                if (!ReferenceEquals(_secondaryPrefCustomers, value))
                {
                    var previousValue = _secondaryPrefCustomers as FixupCollection<Customer>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSecondaryPrefCustomers;
                    }
                    _secondaryPrefCustomers = value;
                    var newValue = value as FixupCollection<Customer>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSecondaryPrefCustomers;
                    }
                }
            }
        }
        private FixupCollection<Customer> _secondaryPrefCustomers;
    
        [DataMember]
    	public FixupCollection<Trip> Trips
        {
            get
            {
                if (_trips == null)
                {
                    var newCollection = new FixupCollection<Trip>();
                    newCollection.CollectionChanged += FixupTrips;
                    _trips = newCollection;
                }
                return _trips;
            }
            set
            {
                if (!ReferenceEquals(_trips, value))
                {
                    var previousValue = _trips as FixupCollection<Trip>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTrips;
                    }
                    _trips = value;
                    var newValue = value as FixupCollection<Trip>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTrips;
                    }
                }
            }
        }
        private FixupCollection<Trip> _trips;
    
        [DataMember]
    	public FixupCollection<Lodging> Lodgings
        {
            get
            {
                if (_lodgings == null)
                {
                    var newCollection = new FixupCollection<Lodging>();
                    newCollection.CollectionChanged += FixupLodgings;
                    _lodgings = newCollection;
                }
                return _lodgings;
            }
            set
            {
                if (!ReferenceEquals(_lodgings, value))
                {
                    var previousValue = _lodgings as FixupCollection<Lodging>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLodgings;
                    }
                    _lodgings = value;
                    var newValue = value as FixupCollection<Lodging>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLodgings;
                    }
                }
            }
        }
        private FixupCollection<Lodging> _lodgings;

        #endregion
        #region Association Fixup
    
        private void FixupPrimaryPrefCustomers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Customer item in e.NewItems)
                {
                    item.PrimaryDestination = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Customer item in e.OldItems)
                {
                    if (ReferenceEquals(item.PrimaryDestination, this))
                    {
                        item.PrimaryDestination = null;
                    }
                }
            }
        }
    
        private void FixupSecondaryPrefCustomers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Customer item in e.NewItems)
                {
                    item.SecondaryDestination = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Customer item in e.OldItems)
                {
                    if (ReferenceEquals(item.SecondaryDestination, this))
                    {
                        item.SecondaryDestination = null;
                    }
                }
            }
        }
    
        private void FixupTrips(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Trip item in e.NewItems)
                {
                    item.Destination = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Trip item in e.OldItems)
                {
                    if (ReferenceEquals(item.Destination, this))
                    {
                        item.Destination = null;
                    }
                }
            }
        }
    
        private void FixupLodgings(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Lodging item in e.NewItems)
                {
                    item.Destination = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Lodging item in e.OldItems)
                {
                    if (ReferenceEquals(item.Destination, this))
                    {
                        item.Destination = null;
                    }
                }
            }
        }

        #endregion
    }
}
