//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch18Console.POCOCustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerNameAndID", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CustomerNameAndID : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateObject", Namespace="http://schemas.datacontract.org/2004/07/POCO.State", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Trip))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Activity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Equipment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Contact))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Address))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Lodging))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Destination))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.CustomerType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Reservation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Payment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.CustomerNameAndID))]
    public partial class StateObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.State StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.State State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trip", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Trip : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Activity> ActivitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Destination DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestinationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Lodging LodgingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LodgingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Reservation> ReservationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TripCostUSDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TripDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TripIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Activity> Activities {
            get {
                return this.ActivitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivitiesField, value) != true)) {
                    this.ActivitiesField = value;
                    this.RaisePropertyChanged("Activities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Destination Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinationID {
            get {
                return this.DestinationIDField;
            }
            set {
                if ((this.DestinationIDField.Equals(value) != true)) {
                    this.DestinationIDField = value;
                    this.RaisePropertyChanged("DestinationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Lodging Lodging {
            get {
                return this.LodgingField;
            }
            set {
                if ((object.ReferenceEquals(this.LodgingField, value) != true)) {
                    this.LodgingField = value;
                    this.RaisePropertyChanged("Lodging");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LodgingID {
            get {
                return this.LodgingIDField;
            }
            set {
                if ((this.LodgingIDField.Equals(value) != true)) {
                    this.LodgingIDField = value;
                    this.RaisePropertyChanged("LodgingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Reservation> Reservations {
            get {
                return this.ReservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationsField, value) != true)) {
                    this.ReservationsField = value;
                    this.RaisePropertyChanged("Reservations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TripCostUSD {
            get {
                return this.TripCostUSDField;
            }
            set {
                if ((this.TripCostUSDField.Equals(value) != true)) {
                    this.TripCostUSDField = value;
                    this.RaisePropertyChanged("TripCostUSD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TripDetails {
            get {
                return this.TripDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.TripDetailsField, value) != true)) {
                    this.TripDetailsField = value;
                    this.RaisePropertyChanged("TripDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TripID {
            get {
                return this.TripIDField;
            }
            set {
                if ((this.TripIDField.Equals(value) != true)) {
                    this.TripIDField = value;
                    this.RaisePropertyChanged("TripID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Activity", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Activity : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActivityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Equipment> EquipmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Customer> PrimaryPrefCustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Customer> SecondaryPrefCustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Trip> TripsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagepathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActivityID {
            get {
                return this.ActivityIDField;
            }
            set {
                if ((this.ActivityIDField.Equals(value) != true)) {
                    this.ActivityIDField = value;
                    this.RaisePropertyChanged("ActivityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Equipment> Equipments {
            get {
                return this.EquipmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentsField, value) != true)) {
                    this.EquipmentsField = value;
                    this.RaisePropertyChanged("Equipments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Customer> PrimaryPrefCustomers {
            get {
                return this.PrimaryPrefCustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPrefCustomersField, value) != true)) {
                    this.PrimaryPrefCustomersField = value;
                    this.RaisePropertyChanged("PrimaryPrefCustomers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Customer> SecondaryPrefCustomers {
            get {
                return this.SecondaryPrefCustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryPrefCustomersField, value) != true)) {
                    this.SecondaryPrefCustomersField = value;
                    this.RaisePropertyChanged("SecondaryPrefCustomers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Trip> Trips {
            get {
                return this.TripsField;
            }
            set {
                if ((object.ReferenceEquals(this.TripsField, value) != true)) {
                    this.TripsField = value;
                    this.RaisePropertyChanged("Trips");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagepath {
            get {
                return this.imagepathField;
            }
            set {
                if ((object.ReferenceEquals(this.imagepathField, value) != true)) {
                    this.imagepathField = value;
                    this.RaisePropertyChanged("imagepath");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipment", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Equipment : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Activity> ActivitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EquipmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Activity> Activities {
            get {
                return this.ActivitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivitiesField, value) != true)) {
                    this.ActivitiesField = value;
                    this.RaisePropertyChanged("Activities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EquipmentID {
            get {
                return this.EquipmentIDField;
            }
            set {
                if ((this.EquipmentIDField.Equals(value) != true)) {
                    this.EquipmentIDField = value;
                    this.RaisePropertyChanged("EquipmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ch18Console.POCOCustomerService.Customer))]
    public partial class Contact : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AddDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Address> AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Lodging> LodgingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AddDate {
            get {
                return this.AddDateField;
            }
            set {
                if ((this.AddDateField.Equals(value) != true)) {
                    this.AddDateField = value;
                    this.RaisePropertyChanged("AddDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Address> Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Lodging> Lodgings {
            get {
                return this.LodgingsField;
            }
            set {
                if ((object.ReferenceEquals(this.LodgingsField, value) != true)) {
                    this.LodgingsField = value;
                    this.RaisePropertyChanged("Lodgings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Address : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Contact ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Mail MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int addressIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressType {
            get {
                return this.AddressTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressTypeField, value) != true)) {
                    this.AddressTypeField = value;
                    this.RaisePropertyChanged("AddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Contact Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegion {
            get {
                return this.CountryRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionField, value) != true)) {
                    this.CountryRegionField = value;
                    this.RaisePropertyChanged("CountryRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Mail Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int addressID {
            get {
                return this.addressIDField;
            }
            set {
                if ((this.addressIDField.Equals(value) != true)) {
                    this.addressIDField = value;
                    this.RaisePropertyChanged("addressID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lodging", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Lodging : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Contact ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Destination DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LocationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LodgingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LodgingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TomorrowForecastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Trip> TripsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Contact Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Destination Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LocationID {
            get {
                return this.LocationIDField;
            }
            set {
                if ((this.LocationIDField.Equals(value) != true)) {
                    this.LocationIDField = value;
                    this.RaisePropertyChanged("LocationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LodgingID {
            get {
                return this.LodgingIDField;
            }
            set {
                if ((this.LodgingIDField.Equals(value) != true)) {
                    this.LodgingIDField = value;
                    this.RaisePropertyChanged("LodgingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LodgingName {
            get {
                return this.LodgingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LodgingNameField, value) != true)) {
                    this.LodgingNameField = value;
                    this.RaisePropertyChanged("LodgingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TomorrowForecast {
            get {
                return this.TomorrowForecastField;
            }
            set {
                if ((object.ReferenceEquals(this.TomorrowForecastField, value) != true)) {
                    this.TomorrowForecastField = value;
                    this.RaisePropertyChanged("TomorrowForecast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Trip> Trips {
            get {
                return this.TripsField;
            }
            set {
                if ((object.ReferenceEquals(this.TripsField, value) != true)) {
                    this.TripsField = value;
                    this.RaisePropertyChanged("Trips");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Destination", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Destination : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestinationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Lodging> LodgingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Customer> PrimaryPrefCustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Customer> SecondaryPrefCustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Trip> TripsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinationID {
            get {
                return this.DestinationIDField;
            }
            set {
                if ((this.DestinationIDField.Equals(value) != true)) {
                    this.DestinationIDField = value;
                    this.RaisePropertyChanged("DestinationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Lodging> Lodgings {
            get {
                return this.LodgingsField;
            }
            set {
                if ((object.ReferenceEquals(this.LodgingsField, value) != true)) {
                    this.LodgingsField = value;
                    this.RaisePropertyChanged("Lodgings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Customer> PrimaryPrefCustomers {
            get {
                return this.PrimaryPrefCustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPrefCustomersField, value) != true)) {
                    this.PrimaryPrefCustomersField = value;
                    this.RaisePropertyChanged("PrimaryPrefCustomers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Customer> SecondaryPrefCustomers {
            get {
                return this.SecondaryPrefCustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryPrefCustomersField, value) != true)) {
                    this.SecondaryPrefCustomersField = value;
                    this.RaisePropertyChanged("SecondaryPrefCustomers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Trip> Trips {
            get {
                return this.TripsField;
            }
            set {
                if ((object.ReferenceEquals(this.TripsField, value) != true)) {
                    this.TripsField = value;
                    this.RaisePropertyChanged("Trips");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Customer : ch18Console.POCOCustomerService.Contact {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] CustRowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.CustomerType CustomerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DietaryRestrictionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HeightInchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InitialDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Activity PrimaryActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PrimaryActivityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Destination PrimaryDestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PrimaryDestinationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Reservation> ReservationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Activity SecondaryActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SecondaryActivityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Destination SecondaryDestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SecondaryDestinationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WeightPoundsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] CustRowVersion {
            get {
                return this.CustRowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.CustRowVersionField, value) != true)) {
                    this.CustRowVersionField = value;
                    this.RaisePropertyChanged("CustRowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.CustomerType CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTypeField, value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerTypeID {
            get {
                return this.CustomerTypeIDField;
            }
            set {
                if ((this.CustomerTypeIDField.Equals(value) != true)) {
                    this.CustomerTypeIDField = value;
                    this.RaisePropertyChanged("CustomerTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DietaryRestrictions {
            get {
                return this.DietaryRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DietaryRestrictionsField, value) != true)) {
                    this.DietaryRestrictionsField = value;
                    this.RaisePropertyChanged("DietaryRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HeightInches {
            get {
                return this.HeightInchesField;
            }
            set {
                if ((this.HeightInchesField.Equals(value) != true)) {
                    this.HeightInchesField = value;
                    this.RaisePropertyChanged("HeightInches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InitialDate {
            get {
                return this.InitialDateField;
            }
            set {
                if ((this.InitialDateField.Equals(value) != true)) {
                    this.InitialDateField = value;
                    this.RaisePropertyChanged("InitialDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Activity PrimaryActivity {
            get {
                return this.PrimaryActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryActivityField, value) != true)) {
                    this.PrimaryActivityField = value;
                    this.RaisePropertyChanged("PrimaryActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PrimaryActivityID {
            get {
                return this.PrimaryActivityIDField;
            }
            set {
                if ((this.PrimaryActivityIDField.Equals(value) != true)) {
                    this.PrimaryActivityIDField = value;
                    this.RaisePropertyChanged("PrimaryActivityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Destination PrimaryDestination {
            get {
                return this.PrimaryDestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryDestinationField, value) != true)) {
                    this.PrimaryDestinationField = value;
                    this.RaisePropertyChanged("PrimaryDestination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PrimaryDestinationID {
            get {
                return this.PrimaryDestinationIDField;
            }
            set {
                if ((this.PrimaryDestinationIDField.Equals(value) != true)) {
                    this.PrimaryDestinationIDField = value;
                    this.RaisePropertyChanged("PrimaryDestinationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Reservation> Reservations {
            get {
                return this.ReservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationsField, value) != true)) {
                    this.ReservationsField = value;
                    this.RaisePropertyChanged("Reservations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Activity SecondaryActivity {
            get {
                return this.SecondaryActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryActivityField, value) != true)) {
                    this.SecondaryActivityField = value;
                    this.RaisePropertyChanged("SecondaryActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SecondaryActivityID {
            get {
                return this.SecondaryActivityIDField;
            }
            set {
                if ((this.SecondaryActivityIDField.Equals(value) != true)) {
                    this.SecondaryActivityIDField = value;
                    this.RaisePropertyChanged("SecondaryActivityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Destination SecondaryDestination {
            get {
                return this.SecondaryDestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryDestinationField, value) != true)) {
                    this.SecondaryDestinationField = value;
                    this.RaisePropertyChanged("SecondaryDestination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SecondaryDestinationID {
            get {
                return this.SecondaryDestinationIDField;
            }
            set {
                if ((this.SecondaryDestinationIDField.Equals(value) != true)) {
                    this.SecondaryDestinationIDField = value;
                    this.RaisePropertyChanged("SecondaryDestinationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WeightPounds {
            get {
                return this.WeightPoundsField;
            }
            set {
                if ((this.WeightPoundsField.Equals(value) != true)) {
                    this.WeightPoundsField = value;
                    this.RaisePropertyChanged("WeightPounds");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerType", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CustomerType : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Customer> CustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerTypeID {
            get {
                return this.CustomerTypeIDField;
            }
            set {
                if ((this.CustomerTypeIDField.Equals(value) != true)) {
                    this.CustomerTypeIDField = value;
                    this.RaisePropertyChanged("CustomerTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Customer> Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Reservation : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ch18Console.POCOCustomerService.Payment> PaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReservationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Trip TripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TripDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TripIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Payment> Payments {
            get {
                return this.PaymentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentsField, value) != true)) {
                    this.PaymentsField = value;
                    this.RaisePropertyChanged("Payments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationDate {
            get {
                return this.ReservationDateField;
            }
            set {
                if ((this.ReservationDateField.Equals(value) != true)) {
                    this.ReservationDateField = value;
                    this.RaisePropertyChanged("ReservationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservationID {
            get {
                return this.ReservationIDField;
            }
            set {
                if ((this.ReservationIDField.Equals(value) != true)) {
                    this.ReservationIDField = value;
                    this.RaisePropertyChanged("ReservationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Trip Trip {
            get {
                return this.TripField;
            }
            set {
                if ((object.ReferenceEquals(this.TripField, value) != true)) {
                    this.TripField = value;
                    this.RaisePropertyChanged("Trip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TripDetails {
            get {
                return this.TripDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.TripDetailsField, value) != true)) {
                    this.TripDetailsField = value;
                    this.RaisePropertyChanged("TripDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TripID {
            get {
                return this.TripIDField;
            }
            set {
                if ((this.TripIDField.Equals(value) != true)) {
                    this.TripIDField = value;
                    this.RaisePropertyChanged("TripID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/BAGA", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Payment : ch18Console.POCOCustomerService.StateObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ch18Console.POCOCustomerService.Reservation ReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReservationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentID {
            get {
                return this.PaymentIDField;
            }
            set {
                if ((this.PaymentIDField.Equals(value) != true)) {
                    this.PaymentIDField = value;
                    this.RaisePropertyChanged("PaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ch18Console.POCOCustomerService.Reservation Reservation {
            get {
                return this.ReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationField, value) != true)) {
                    this.ReservationField = value;
                    this.RaisePropertyChanged("Reservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReservationID {
            get {
                return this.ReservationIDField;
            }
            set {
                if ((this.ReservationIDField.Equals(value) != true)) {
                    this.ReservationIDField = value;
                    this.RaisePropertyChanged("ReservationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/POCO.State")]
    public enum State : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mail", Namespace="http://schemas.datacontract.org/2004/07/BAGA")]
    [System.SerializableAttribute()]
    public partial class Mail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateProvince {
            get {
                return this.StateProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvinceField, value) != true)) {
                    this.StateProvinceField = value;
                    this.RaisePropertyChanged("StateProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street1 {
            get {
                return this.Street1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street1Field, value) != true)) {
                    this.Street1Field = value;
                    this.RaisePropertyChanged("Street1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street2 {
            get {
                return this.Street2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street2Field, value) != true)) {
                    this.Street2Field = value;
                    this.RaisePropertyChanged("Street2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="POCOCustomerService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerPickList", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerPickListResponse")]
        System.Collections.Generic.List<ch18Console.POCOCustomerService.CustomerNameAndID> GetCustomerPickList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetUpcomingTrips", ReplyAction="http://tempuri.org/ICustomerService/GetUpcomingTripsResponse")]
        System.Collections.Generic.List<ch18Console.POCOCustomerService.Trip> GetUpcomingTrips();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomer", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerResponse")]
        ch18Console.POCOCustomerService.Customer GetCustomer(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/SaveCustomer", ReplyAction="http://tempuri.org/ICustomerService/SaveCustomerResponse")]
        string SaveCustomer(ch18Console.POCOCustomerService.Customer cust);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : ch18Console.POCOCustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<ch18Console.POCOCustomerService.ICustomerService>, ch18Console.POCOCustomerService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.CustomerNameAndID> GetCustomerPickList() {
            return base.Channel.GetCustomerPickList();
        }
        
        public System.Collections.Generic.List<ch18Console.POCOCustomerService.Trip> GetUpcomingTrips() {
            return base.Channel.GetUpcomingTrips();
        }
        
        public ch18Console.POCOCustomerService.Customer GetCustomer(int customerId) {
            return base.Channel.GetCustomer(customerId);
        }
        
        public string SaveCustomer(ch18Console.POCOCustomerService.Customer cust) {
            return base.Channel.SaveCustomer(cust);
        }
    }
}
