<?xml version="1.0" encoding="utf-8"?><Database Name="AdventureWorksLT" Class="AWL2SDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=honker64;Initial Catalog=AdventureWorksLT;Integrated Security=True" SettingsObjectName="Chapter20ConsolePerf.Properties.Settings" SettingsPropertyName="AdventureWorksLTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="SalesLT.Customer" Member="L2SCustomers">
    <Type Name="L2SCustomer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameStyle" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Suffix" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SalesPerson" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>