//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace BAGA
{
    public partial class TripPayment
    {
        #region Primitive Properties
    
        public System.DateTime PaymentDate
        {
            get;
            set;
        }
    
        public decimal Amount
        {
            get;
            set;
        }
    
        public System.DateTime ReservationDate
        {
            get;
            set;
        }
    
        public string FirstName
        {
            get;
            set;
        }
    
        public string LastName
        {
            get;
            set;
        }
    
        public System.DateTime StartDate
        {
            get;
            set;
        }
    
        public System.DateTime EndDate
        {
            get;
            set;
        }
    
        public string LocationName
        {
            get;
            set;
        }

        #endregion
    }
}
