//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace BAGA
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Customer))]
    [KnownType(typeof(Trip))]
    [KnownType(typeof(Lodging))]
    public partial class Destination: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int DestinationID
        {
            get { return _destinationID; }
            set
            {
                if (_destinationID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'DestinationID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _destinationID = value;
                    OnPropertyChanged("DestinationID");
                }
            }
        }
        private int _destinationID;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Customer> PrimaryPrefCustomers
        {
            get
            {
                if (_primaryPrefCustomers == null)
                {
                    _primaryPrefCustomers = new TrackableCollection<Customer>();
                    _primaryPrefCustomers.CollectionChanged += FixupPrimaryPrefCustomers;
                }
                return _primaryPrefCustomers;
            }
            set
            {
                if (!ReferenceEquals(_primaryPrefCustomers, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_primaryPrefCustomers != null)
                    {
                        _primaryPrefCustomers.CollectionChanged -= FixupPrimaryPrefCustomers;
                    }
                    _primaryPrefCustomers = value;
                    if (_primaryPrefCustomers != null)
                    {
                        _primaryPrefCustomers.CollectionChanged += FixupPrimaryPrefCustomers;
                    }
                    OnNavigationPropertyChanged("PrimaryPrefCustomers");
                }
            }
        }
        private TrackableCollection<Customer> _primaryPrefCustomers;
    
        [DataMember]
        public TrackableCollection<Customer> SecondaryPrefCustomers
        {
            get
            {
                if (_secondaryPrefCustomers == null)
                {
                    _secondaryPrefCustomers = new TrackableCollection<Customer>();
                    _secondaryPrefCustomers.CollectionChanged += FixupSecondaryPrefCustomers;
                }
                return _secondaryPrefCustomers;
            }
            set
            {
                if (!ReferenceEquals(_secondaryPrefCustomers, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_secondaryPrefCustomers != null)
                    {
                        _secondaryPrefCustomers.CollectionChanged -= FixupSecondaryPrefCustomers;
                    }
                    _secondaryPrefCustomers = value;
                    if (_secondaryPrefCustomers != null)
                    {
                        _secondaryPrefCustomers.CollectionChanged += FixupSecondaryPrefCustomers;
                    }
                    OnNavigationPropertyChanged("SecondaryPrefCustomers");
                }
            }
        }
        private TrackableCollection<Customer> _secondaryPrefCustomers;
    
        [DataMember]
        public TrackableCollection<Trip> Trips
        {
            get
            {
                if (_trips == null)
                {
                    _trips = new TrackableCollection<Trip>();
                    _trips.CollectionChanged += FixupTrips;
                }
                return _trips;
            }
            set
            {
                if (!ReferenceEquals(_trips, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_trips != null)
                    {
                        _trips.CollectionChanged -= FixupTrips;
                    }
                    _trips = value;
                    if (_trips != null)
                    {
                        _trips.CollectionChanged += FixupTrips;
                    }
                    OnNavigationPropertyChanged("Trips");
                }
            }
        }
        private TrackableCollection<Trip> _trips;
    
        [DataMember]
        public TrackableCollection<Lodging> Lodgings
        {
            get
            {
                if (_lodgings == null)
                {
                    _lodgings = new TrackableCollection<Lodging>();
                    _lodgings.CollectionChanged += FixupLodgings;
                }
                return _lodgings;
            }
            set
            {
                if (!ReferenceEquals(_lodgings, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_lodgings != null)
                    {
                        _lodgings.CollectionChanged -= FixupLodgings;
                    }
                    _lodgings = value;
                    if (_lodgings != null)
                    {
                        _lodgings.CollectionChanged += FixupLodgings;
                    }
                    OnNavigationPropertyChanged("Lodgings");
                }
            }
        }
        private TrackableCollection<Lodging> _lodgings;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PrimaryPrefCustomers.Clear();
            SecondaryPrefCustomers.Clear();
            Trips.Clear();
            Lodgings.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupPrimaryPrefCustomers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Customer item in e.NewItems)
                {
                    item.PrimaryDestination = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PrimaryPrefCustomers", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Customer item in e.OldItems)
                {
                    if (ReferenceEquals(item.PrimaryDestination, this))
                    {
                        item.PrimaryDestination = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PrimaryPrefCustomers", item);
                    }
                }
            }
        }
    
        private void FixupSecondaryPrefCustomers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Customer item in e.NewItems)
                {
                    item.SecondaryDestination = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("SecondaryPrefCustomers", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Customer item in e.OldItems)
                {
                    if (ReferenceEquals(item.SecondaryDestination, this))
                    {
                        item.SecondaryDestination = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("SecondaryPrefCustomers", item);
                    }
                }
            }
        }
    
        private void FixupTrips(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Trip item in e.NewItems)
                {
                    item.Destination = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Trips", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Trip item in e.OldItems)
                {
                    if (ReferenceEquals(item.Destination, this))
                    {
                        item.Destination = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Trips", item);
                    }
                }
            }
        }
    
        private void FixupLodgings(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Lodging item in e.NewItems)
                {
                    item.Destination = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Lodgings", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Lodging item in e.OldItems)
                {
                    if (ReferenceEquals(item.Destination, this))
                    {
                        item.Destination = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Lodgings", item);
                    }
                }
            }
        }

        #endregion
    }
}
