//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace BAGA
{
    public partial class Mail
    {
        #region Primitive Properties
    
        public string Street1
        {
            get;
            set;
        }
    
        public string Street2
        {
            get;
            set;
        }
    
        public string City
        {
            get;
            set;
        }
    
        public string StateProvince
        {
            get;
            set;
        }

        #endregion
    }
}
