//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace BAGA
{
    	[Serializable()]
        [DataContractAttribute(IsReference=true)]
    public partial class vPaymentsforPeriod : POCO.State.StateObject
    {
        #region Primitive Properties
        [DataMember]
         public Nullable<System.DateTime> PaymentDate
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public Nullable<decimal> Amount
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public System.DateTime ReservationDate
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public string FirstName
        {
    		   get{return _firstName;} 
    			set
     				{
    					if (value != null && value.Length > 50) 
    					 {throw new ArgumentException("FirstName must be less than 50 characters");}
    			    else
      				{ _firstName = value;}
    				}
    
    	
        }
        private string _firstName;
        [DataMember]
         public string LastName
        {
    		   get{return _lastName;} 
    			set
     				{
    					if (value != null && value.Length > 50) 
    					 {throw new ArgumentException("LastName must be less than 50 characters");}
    			    else
      				{ _lastName = value;}
    				}
    
    	
        }
        private string _lastName;
        [DataMember]
         public System.DateTime StartDate
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public System.DateTime EndDate
        {
    	        get;
    		set;
    	
        }
        [DataMember]
         public string LocationName
        {
    		   get{return _locationName;} 
    			set
     				{
    					if (value != null && value.Length > 50) 
    					 {throw new ArgumentException("LocationName must be less than 50 characters");}
    			    else
      				{ _locationName = value;}
    				}
    
    	
        }
        private string _locationName;

        #endregion
    }
}
