//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace BAGA
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Reservation))]
    public partial class Payment: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int PaymentID
        {
            get { return _paymentID; }
            set
            {
                if (_paymentID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PaymentID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _paymentID = value;
                    OnPropertyChanged("PaymentID");
                }
            }
        }
        private int _paymentID;
    
        [DataMember]
        public Nullable<System.DateTime> PaymentDate
        {
            get { return _paymentDate; }
            set
            {
                if (_paymentDate != value)
                {
                    _paymentDate = value;
                    OnPropertyChanged("PaymentDate");
                }
            }
        }
        private Nullable<System.DateTime> _paymentDate;
    
        [DataMember]
        public Nullable<int> ReservationID
        {
            get { return _reservationID; }
            set
            {
                if (_reservationID != value)
                {
    //julie was here
                    ChangeTracker.RecordOriginalValue("ReservationID", _reservationID);
                    if (!IsDeserializing)
                    {
                        if (Reservation != null && Reservation.ReservationID != value)
                        {
                            Reservation = null;
                        }
                    }
                    _reservationID = value;
                    OnPropertyChanged("ReservationID");
                }
            }
        }
        private Nullable<int> _reservationID;
    
        [DataMember]
        public Nullable<decimal> Amount
        {
            get { return _amount; }
            set
            {
                if (_amount != value)
                {
                    _amount = value;
                    OnPropertyChanged("Amount");
                }
            }
        }
        private Nullable<decimal> _amount;
    
        [DataMember]
        public System.DateTime ModifiedDate
        {
            get { return _modifiedDate; }
            set
            {
                if (_modifiedDate != value)
                {
                    _modifiedDate = value;
                    OnPropertyChanged("ModifiedDate");
                }
            }
        }
        private System.DateTime _modifiedDate;
    
        [DataMember]
        public byte[] TimeStamp
        {
            get { return _timeStamp; }
            set
            {
                if (_timeStamp != value)
                {
                    _timeStamp = value;
                    OnPropertyChanged("TimeStamp");
                }
            }
        }
        private byte[] _timeStamp;
    
        [DataMember]
        public Nullable<int> ContactID
        {
            get { return _contactID; }
            set
            {
                if (_contactID != value)
                {
                    _contactID = value;
                    OnPropertyChanged("ContactID");
                }
            }
        }
        private Nullable<int> _contactID;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Reservation Reservation
        {
            get { return _reservation; }
            set
            {
                if (!ReferenceEquals(_reservation, value))
                {
                    var previousValue = _reservation;
                    _reservation = value;
                    FixupReservation(previousValue);
                    OnNavigationPropertyChanged("Reservation");
                }
            }
        }
        private Reservation _reservation;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Reservation = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupReservation(Reservation previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Payments.Contains(this))
            {
                previousValue.Payments.Remove(this);
            }
    
            if (Reservation != null)
            {
                if (!Reservation.Payments.Contains(this))
                {
                    Reservation.Payments.Add(this);
                }
    
                ReservationID = Reservation.ReservationID;
            }
            else if (!skipKeys)
            {
                ReservationID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Reservation")
                    && (ChangeTracker.OriginalValues["Reservation"] == Reservation))
                {
                    ChangeTracker.OriginalValues.Remove("Reservation");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Reservation", previousValue);
                }
                if (Reservation != null && !Reservation.ChangeTracker.ChangeTrackingEnabled)
                {
                    Reservation.StartTracking();
                }
            }
        }

        #endregion
    }
}
